# shape : 배열의 크기 확인

넘파이에서 배열의 구조(행과 열의 개수)를 알고 싶을 때는 shape 속성을 사용한다.

shape 속성은 배열의 차원별 크기를 튜플 형태로 반환한다.

In [1]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(arr.shape)        # 출력 : (3, 4)
print(np.shape(arr))    # 출력 : (3, 4)


(3, 4)
(3, 4)


# ndim : 배열의 차원 확인

ndim 은 넘파이 배열이 몇 차원(몇 개의 축)인지 알려주는 속성이다.

shape는 배열의 각 차원이 몇 개의 요소를 갖고 있는지 구조(모양) 를 튜플로 반환한다.

예를 들어 (4, 3)은 4행 3열 구조이고, ndim은 이것이 2차원 배열이라는 사실만 알려준다.

In [12]:
import numpy as np

arr1 = np.array(7)                    # 0차원
arr2 = np.array([1, 2, 3])            # 1차원
arr3 = np.array([[1, 2], [3, 4]])     # 2차원
arr4 = np.array([[[111, 112, 113],
                 [121, 122, 123]],
                [[211, 212, 213],
                 [221, 222, 223]]])

print(arr1.ndim)    # 출력 : 0
print(arr2.ndim)    # 출력 : 1
print(arr3.ndim)    # 출력 : 2
print(arr4.ndim)    # 출력 : 3


0
1
2
3


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new1 = arr.reshape(3, 4)    # 2차원 : 4행 3열
new2 = arr.reshape(6, 2)    # 2차원 : 2행 6열

print(new1, '\n')     # 출력 : 4행 3열 데이터
print(new2, '\n')     # 출력 : 2행 6열 데이터

print(new1.ndim)      # 출력 : 2
print(new2.shape)     # 출력 : (2, 6)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

2
(6, 2)


# reshape() : 배열 모양 변경

배열 재구성(reshape)은 데이터를 변경하지 않고 배열의 크기를 변경하는 것을 말한다.

reshape 는 배열의 차원과 구조를 원하는 모양으로 재구성하는 속성이다.
원소 개수는 유지되어야 하며, 자동 계산을 위해 -1을 사용할 수도 있다.

In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_2d = np.array([[1, 2], [3, 4]])     # 2차원

arr_cv1 = arr_2d.reshape(-1)
print(arr_cv1)
print('>>>>>>>>>>>>>>>')

arr1 = arr.reshape(4, -1)
print(arr1)         # 출력 : 2행, 3열의 2차원 배열로 변경
# 출력:
# [[1 2 3]
#  [4 5 6]]

arr2 = arr.reshape(-1, 2)    # -1은 자동으로 계산하라는 의미
print(arr2)    # 출력 : (?, 2)에서 ? 자리에 알맞은 수가 자동으로 채워짐
# 출력:
# [[1 2]
#  [3 4]
#  [5 6]]

arr3 = arr.reshape(-1, 4)    # -1은 자동으로 계산하라는 의미
print(arr3)    # 출력 : (?, 2)에서 ? 자리에 알맞은 수가 자동으로 채워짐


[1 2 3 4]
>>>>>>>>>>>>>>>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
img_rd_data = np.arange(1, 64)
print ("흑백 64픽셀 데이터 : ", img_rd_data)

rgb_data = img_rd_data.reshape(-1,3)
print ("3채널 64픽셀 데이터 : ", rgb_data)

흑백 64픽셀 데이터 :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
3채널 64픽셀 데이터 :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]
 [55 56 57]
 [58 59 60]
 [61 62 63]]


In [29]:
daily_cnt = np.array([
    10, 20, 40, 29, 84,19, 23, 10, 20, 40, 29, 84,19, 23, 10, 20, 40, 29, 84,19, 23,10, 20, 40, 29, 84,19, 23
])
weekly_cnt = daily_cnt.reshape(-1,7)
print('주별 내역 : ', weekly_cnt)

weekly_avg = weekly_cnt.mean(axis=1)
print('평균 : ', weekly_avg)


주별 내역 :  [[10 20 40 29 84 19 23]
 [10 20 40 29 84 19 23]
 [10 20 40 29 84 19 23]
 [10 20 40 29 84 19 23]]
평균 :  [32.14285714 32.14285714 32.14285714 32.14285714]


데이터 12개가 저장된 1차원 배열을 (4, 3) 형태 또는 (2, 6) 형태의 2차원 배열로 재구성한다.

방법 1 : 넘파이 배열로 변환 후 reshape

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new1 = arr.reshape(4, 3)
new2 = arr.reshape(2, 6)

print(new1, '\n')   # 출력 : 4행 3열 데이터
print(new2)         # 출력 : 2행 6열 데이터


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


방법 2 : 리스트를 reshape에 바로 넣기

In [6]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]     # 리스트 형태

new1 = np.reshape(a, (4, 3))
new2 = np.reshape(a, (2, 6))

print(new1, '\n')   # 출력 : 4행 3열 데이터
print(new2)         # 출력 : 2행 6열 데이터


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


데이터 12개가 저장된 1차원 배열을 (2, 3, 2) 형태의 3차원 배열로 재구성한다.

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
newarr      # 출력 : 3차원 배열 데이터


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# flatten() : 배열을 1차원으로 펼치기

In [8]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)    # 출력 : [1 2 3 4]


[1 2 3 4]


# transpose() : 전치 (행 ↔ 열 교환)

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

dap = arr.transpose()
print(dap)
# 출력 :
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


# 배열의 차원 수를 확장하기

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)              # 출력 : (6,) → 1차원

arr_col = arr[:, np.newaxis]  # np.newaxis가 뒤에 있으므로 → 열 차원을 추가
print(arr_col.shape)          # 출력 : (6, 1) → 열 벡터 (2차원)

# arr.reshape(-1, 1)은 동일한 결과를 얻을 수 있다.
# 가상 출력 :
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]
#  [6]]


(6,)
(6, 1)


In [2]:
import numpy as np

arr_row = arr[np.newaxis, :]  # np.newaxis가 앞에 있으므로 → 행 차원을 추가
print(arr_row.shape)          # 출력 : (1, 6) → 행 벡터 (2차원)

# arr.reshape(1, -1)은 동일한 결과를 얻을 수 있다.
# 가상 출력 : [1 2 3 4 5 6]


NameError: name 'arr' is not defined

In [ ]:
import numpy as np
# 학생별 과목 점수 데이터
students_scores = np.array([
    [90, 85, 88],  # 학생1: 수학, 영어, 과학
    [78, 92, 85],  # 학생2
    [88, 79, 91],  # 학생3
    [95, 88, 87],  # 학생4
    [82, 90, 93]   # 학생5
])

print("학생별 점수 (행: 학생, 열: 과목):")
print(students_scores)
print("Shape:", students_scores.shape)  # (5, 3)

# 과목별 점수로 변환
subjects_scores = students_scores.T #students_scores.transpose()
print("\n과목별 점수 (행: 과목, 열: 학생):")
print(subjects_scores)
print("Shape:", subjects_scores.shape)  # (3, 5)

# 과목별 평균 계산
subject_means = np.mean(subjects_scores, axis=1)
subjects = ['수학', '영어', '과학']
for i, subject in enumerate(subjects):
    print(f"{subject} 평균: {subject_means[i]:.1f}")

# 학생별 평균 계산
student_means = np.mean(students_scores, axis=1)
for i, mean in enumerate(student_means):
    print(f"학생{i+1} 평균: {mean:.1f}")

학생별 점수 (행: 학생, 열: 과목):
[[90 85 88]
 [78 92 85]
 [88 79 91]
 [95 88 87]
 [82 90 93]]
Shape: (5, 3)

과목별 점수 (행: 과목, 열: 학생):
[[90 78 88 95 82]
 [85 92 79 88 90]
 [88 85 91 87 93]]
Shape: (3, 5)
수학 평균: 86.6
영어 평균: 86.8
과학 평균: 88.8
학생1 평균: 87.7
학생2 평균: 85.0
학생3 평균: 86.0
학생4 평균: 90.0
학생5 평균: 88.3


In [4]:
# 판매 데이터 (월별 제품 판매량)
sales_data = np.array([
    [100, 120, 110, 130],  # 1월: 제품A,B,C,D
    [110, 130, 120, 140],  # 2월
    [120, 125, 130, 145],  # 3월
    [130, 135, 125, 150],  # 4월
    [125, 140, 135, 155],  # 5월
    [135, 145, 140, 160]   # 6월
])

months = ['1월', '2월', '3월', '4월', '5월', '6월']
products = ['제품A', '제품B', '제품C', '제품D']

print("월별 제품 판매량:")
for i, month in enumerate(months):
    print(f"{month}: {sales_data[i]}")

# 제품별 월간 판매량으로 전환
product_sales = sales_data.T
print("\n제품별 월간 판매량:")
for i, product in enumerate(products):
    print(f"{product}: {product_sales[i]}")
    
# 제품별 총 판매량과 평균
print("\n제품별 통계:")
for i, product in enumerate(products):
    total = np.sum(product_sales[i])
    avg = np.mean(product_sales[i])
    print(f"{product}: 총 {total}개, 평균 {avg:.1f}개/월")

월별 제품 판매량:
1월: [100 120 110 130]
2월: [110 130 120 140]
3월: [120 125 130 145]
4월: [130 135 125 150]
5월: [125 140 135 155]
6월: [135 145 140 160]

제품별 월간 판매량:
제품A: [100 110 120 130 125 135]
제품B: [120 130 125 135 140 145]
제품C: [110 120 130 125 135 140]
제품D: [130 140 145 150 155 160]

제품별 통계:
제품A: 총 720개, 평균 120.0개/월
제품B: 총 795개, 평균 132.5개/월
제품C: 총 760개, 평균 126.7개/월
제품D: 총 880개, 평균 146.7개/월
