# 검색

배열에서 짝수 데이터에 대한 인덱스를 찾아준다.

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(a % 2 == 0)
print(x)      # 출력 : array([1, 3, 5, 7])


(array([1, 3, 5, 7]),)


배열에서 홀수 데이터에 대한 인덱스를 찾아준다.

In [7]:
import numpy as np
a = np.array([12, 21, 34, 44, 55, 65, 75, 85])

x = np.where(a % 2 == 1)
print(x)      # 출력 : array([0, 2, 4, 6])


(array([1, 4, 5, 6, 7]),)


In [3]:
import numpy as np
a = [[11, 12, 13, 14, 15],
     [21, 22, 30, 24, 25]]

print(np.argmax(a))             # 출력 : 7

print('------------')
print(np.argmin(a))             # 출력 : 0



7
------------
0


In [ ]:
import numpy as np
a = np.array([[31, 12, 33, 14, 35],
              [21, 22, 23, 24, 25]])

print(np.argwhere(a == 33))     # 출력 : [[0 2]] → 조건을 만족하는 값의 위치(인덱스)를 반환
print(np.where(a == 33))     # 출력 : (array([0]), array([2])) → 조건을 만족하는 값의 위치(인덱스)를 반환
print(np.extract(a > 30, a))    # 출력 : [31 33 35] → 조건을 만족하는 값만을 추출


[[0 2]]
(array([0]), array([2]))
[31 33 35]


In [5]:
import numpy as np

# 학생 시험 점수 데이터
scores = np.array([[85, 92, 78, 95, 88],
                   [76, 89, 94, 82, 91],
                   [90, 85, 87, 93, 86]])

print("학생별 점수:")
print(scores)
print()

# 90점 이상인 점수의 위치 찾기
high_score_positions = np.argwhere(scores >= 90)
print("90점 이상인 점수의 위치 (행, 열):")
print(high_score_positions)

# 90점 이상인 점수만 추출
high_scores = np.extract(scores >= 90, scores)
print("90점 이상인 점수들:")
print(high_scores)

# 특정 점수 찾기
target_score = 94
target_positions = np.argwhere(scores == target_score)
print(f"\n{target_score}점인 위치:")
print(target_positions)

학생별 점수:
[[85 92 78 95 88]
 [76 89 94 82 91]
 [90 85 87 93 86]]

90점 이상인 점수의 위치 (행, 열):
[[0 1]
 [0 3]
 [1 2]
 [1 4]
 [2 0]
 [2 3]]
90점 이상인 점수들:
[92 95 94 91 90 93]

94점인 위치:
[[1 2]]


In [6]:
# 월별 지역별 판매량 데이터
sales_data = np.array([
    [120, 150, 180, 200, 175],  # 1월: 서울, 부산, 대구, 광주, 대전
    [135, 165, 190, 210, 185],  # 2월
    [145, 175, 200, 220, 195],  # 3월
    [160, 180, 215, 235, 205],  # 4월
    [155, 185, 205, 225, 200],  # 5월
    [170, 195, 220, 245, 215]   # 6월
])

months = ['1월', '2월', '3월', '4월', '5월', '6월']
cities = ['서울', '부산', '대구', '광주', '대전']

print("월별 지역별 판매량:")
print(sales_data)
print()

# 200개 이상 판매한 경우 찾기
high_sales_pos = np.argwhere(sales_data >= 200)
high_sales_values = np.extract(sales_data >= 200, sales_data)

print("200개 이상 판매 실적:")
for i, pos in enumerate(high_sales_pos):
    month_idx, city_idx = pos
    value = high_sales_values[i]
    print(f"  {months[month_idx]} {cities[city_idx]}: {value}개")

# 최고 판매량 위치
max_pos = np.argwhere(sales_data == np.max(sales_data))
print(f"\n최고 판매량 위치: {months[max_pos[0][0]]} {cities[max_pos[0][1]]}")
print(f"최고 판매량: {np.max(sales_data)}개")

# 평균 이하 판매량
avg_sales = np.mean(sales_data)
below_avg_pos = np.argwhere(sales_data < avg_sales)
below_avg_values = np.extract(sales_data < avg_sales, sales_data)
print(f"\n평균({avg_sales:.1f}) 이하 판매 실적 {len(below_avg_values)}건:")
print(f"해당 판매량들: {below_avg_values}")

월별 지역별 판매량:
[[120 150 180 200 175]
 [135 165 190 210 185]
 [145 175 200 220 195]
 [160 180 215 235 205]
 [155 185 205 225 200]
 [170 195 220 245 215]]

200개 이상 판매 실적:
  1월 광주: 200개
  2월 광주: 210개
  3월 대구: 200개
  3월 광주: 220개
  4월 대구: 215개
  4월 광주: 235개
  4월 대전: 205개
  5월 대구: 205개
  5월 광주: 225개
  5월 대전: 200개
  6월 대구: 220개
  6월 광주: 245개
  6월 대전: 215개

최고 판매량 위치: 6월 광주
최고 판매량: 245개

평균(188.5) 이하 판매 실적 14건:
해당 판매량들: [120 150 180 175 135 165 185 145 175 160 180 155 185 170]
