# 슬라이싱

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]      # 출력 : [2, 3, 4, 5]


array([2, 3, 4, 5])

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[4:]      # 출력 : [5, 6, 7]


array([5, 6, 7])

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]      # 출력 : [1, 2, 3, 4]


array([1, 2, 3, 4])

# 네거티브 슬라이싱

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])       # 출력 : [5, 6]
print(arr[-1:-8:-1])    # 출력 : [7, 6, 5, 4, 3, 2, 1]


[5 6]
[7 6 5 4 3 2 1]


# 단계별 슬라이싱

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5:2]     # 출력 : [2, 4]


array([2, 4])

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])   # 처음부터 2씩 증가하며 슬라이싱 한다.
arr[::2]     #  출력 : [1, 3, 5, 7]


array([1, 3, 5, 7])

# 2-차원 배열 슬라이싱

In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]      # 출력 : [7, 8, 9]


array([7, 8, 9])

In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 2]     # 출력 : [3, 8]


array([3, 8])

# 예제

In [13]:
import numpy as np
arr =np.array([['20251147', '박세은', 88, 94, 69],
              ['20241129', '이하늘', 69, 69, 89],
              ['20232458', '박서연', 52, 93, 73],
              ['20231244', '최수빈', 79, 97, 95],
              ['20251002', '김예린', 55, 74, 61],
              ['20242387', '정민수', 76, 80, 70],
              ['20232499', '장도윤', 67, 89, 55],
              ['20251236', '윤지우', 98, 65, 86],
              ['20242569', '강하늘', 60, 97, 83],
              ['20231288', '조지민', 79, 62, 93]])


In [14]:
kor = arr[:, 2].astype(int)
eng = arr[:, 3].astype(int)
mat = arr[:, 4].astype(int)
# 1. 국어 성적의 합계
print(np.sum(kor), '\n')    # 출력 : 723
# 2. 영어 성적의 평균
print(np.sum(eng), '\n')    # 출력 : 820
# 3. 수학 성적의 표준편차
print(np.std(mat), '\n')    # 출력 : 13.070577645995606
# 4. 국어, 영어, 수학 점수의 합계(학생별)
# np.add() 함수는 두 개의 배열 입력 가능 → np.add()를 2단계로 중첩 사용
total =  np.add(np.add(kor, eng), mat)
print(total, '\n')          # 출력 : [251 227 218 271 190 226 211 249 240 234]

# 5. 국어, 영어, 수학 점수의 평균(학생별)
avg = np.round(total / 3)
print(avg, '\n')            # 출력 : [84. 76. 73. 90. 63. 75. 70. 83. 80. 78.]


723 

820 

13.070577645995606 

[251 227 218 271 190 226 211 249 240 234] 

[84. 76. 73. 90. 63. 75. 70. 83. 80. 78.] 



In [15]:
# 1. 국영수 점수 추출 및 int 변환
kor = arr[:, 2].astype(int)
eng = arr[:, 3].astype(int)
mat = arr[:, 4].astype(int)
# 2. 총점 및 평균 계산
total = kor + eng + mat
avg = np.round(total / 3, 1)  # 소수 첫째자리까지 반올림
# 3. 총점을 원본 배열에 추가
arr_total = np.hstack((arr, total.reshape(-1, 1)))
print(arr_total, '\n')
# 4. 평균을 원본 배열에 추가
arr_avg = np.hstack((arr, avg.reshape(-1, 1)))
print(arr_avg, '\n')
# 5. 총점과 평균을 함께 원본 배열에 추가
arr_score = np.hstack((arr, total.reshape(-1, 1), avg.reshape(-1, 1)))
print(arr_score, '\n')
# 6. 평균 기준으로 내림차순 정렬
arr_sort = arr_score[avg.argsort()[::-1]]
print(arr_sort, '\n')
# 7. 필드명(제목 행)을 추가하기
header = np.array(["번호", "이름", "국어", "영어", "수학", "총점", "평균"])  # 2차원 배열로 변환 (1행 7열)
arr_header = np.vstack((header, arr_sort))
print(arr_header, '\n')
# 8. 최고점자와 최저점자
student_high = arr_sort[0]
student_low = arr_sort[-1]

print('--------------------------------')
print('평균 최고점자 = ', student_high[1], f'({student_high[6]}점)')
print('평균 최저점자 = ', student_low[1], f'({student_low[6]}점)')


[['20251147' '박세은' '88' '94' '69' '251']
 ['20241129' '이하늘' '69' '69' '89' '227']
 ['20232458' '박서연' '52' '93' '73' '218']
 ['20231244' '최수빈' '79' '97' '95' '271']
 ['20251002' '김예린' '55' '74' '61' '190']
 ['20242387' '정민수' '76' '80' '70' '226']
 ['20232499' '장도윤' '67' '89' '55' '211']
 ['20251236' '윤지우' '98' '65' '86' '249']
 ['20242569' '강하늘' '60' '97' '83' '240']
 ['20231288' '조지민' '79' '62' '93' '234']] 

[['20251147' '박세은' '88' '94' '69' '83.7']
 ['20241129' '이하늘' '69' '69' '89' '75.7']
 ['20232458' '박서연' '52' '93' '73' '72.7']
 ['20231244' '최수빈' '79' '97' '95' '90.3']
 ['20251002' '김예린' '55' '74' '61' '63.3']
 ['20242387' '정민수' '76' '80' '70' '75.3']
 ['20232499' '장도윤' '67' '89' '55' '70.3']
 ['20251236' '윤지우' '98' '65' '86' '83.0']
 ['20242569' '강하늘' '60' '97' '83' '80.0']
 ['20231288' '조지민' '79' '62' '93' '78.0']] 

[['20251147' '박세은' '88' '94' '69' '251' '83.7']
 ['20241129' '이하늘' '69' '69' '89' '227' '75.7']
 ['20232458' '박서연' '52' '93' '73' '218' '72.7']
 ['20231244' '최수빈' '